# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2453e19e-eb3c-4c1d-9ce1-5fe32ff0ea54";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2453e19e-eb3c-4c1d-9ce1-5fe32ff0ea54".device = "/dev/disk/by-uuid/2453e19e-eb3c-4c1d-9ce1-5fe32ff0ea54";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6DB9-16C7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-820a8158-1ee3-4d1d-a7cb-d670c6b7e094"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
